### ISSUE TITLE
Lime trees dissapearing

### ISSUE THREAD

**Issue by grandphoenix663** [brnbrd/VeggieDelight#15]
**Describe the bug**: planted 12 lime trees, went afk for a few minutes and came back and 9 disappeared, all before the flowering stage

**To Reproduce**: Plant multiple lime trees in area, wait

**Expected behavior**: for them to not dissapear

**Screenshots**: 
![2023-04-25_20 40 23](https://user-images.githubusercontent.com/130688670/234465129-abb0674d-11a5-4282-b983-2d0530f985f3.png)

**Versions**: Farmers Delight: 1.2 Collector's Reap 1.2.3
(Cottage Witch Modpack 1.14.0a 1.19.2)

**Comment by katubug** [comment]
A note about this: in our forge server config, erroring block entities are set to be removed upon error rather than crash. I'm unsure if this is the cause of the disappearing, but if it is, I'd look into what kind of error they could be throwing?

I'll try to get you the server's latest.log shortly here

**Comment by brnbrd** [comment]
Please show me you can reproduce this in a minimal environment
